map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
    global_costmap:
      global_costmap:
        ros__parameters:
          use_sim_time: true
          global_frame: map
          robot_base_frame: base_footprint
          update_frequency: 1.0
          publish_frequency: 1.0
          resolution: 0.05
          robot_radius: 0.22
          plugins: ["static_layer", "inflation_layer"]
          static_layer:
            plugin: "nav2_costmap_2d::StaticLayer"
            map_subscribe_transient_local: true
            enabled: true
          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            cost_scaling_factor: 3.0
            inflation_radius: 0.30
          always_send_full_costmap: true
